Go 中，错误用内建的 `error` 类型来表示。

就像其他的内建类型（如 `int`、`float64` 等），错误值可以存储在变量里、作为函数的返回值等等。
```go
func main() {  
    f, err := os.Open("/test.txt")   //打开不存在的文件
    if err != nil {          //如果 error 不为 nil，也就是发生了错误
        fmt.Println(err)
        return
    }
    fmt.Println(f.Name(), "opened successfully")
}
```
其中 `os` 包中的 `Open` 函数签名为
```go
func Open(name string) (file *File, err error)
```
如果成功打开文件，`Open` 函数会返回一个文件句柄和一个值为 `nil`的错误(error)。而如果打开文件时发生了错误，会返回一个不等于 `nil` 的错误。

如果一个函数 或方法 返回了错误，按照惯例，错误作为最后一个值返回。`Open` 函数也是将 `err` 作为最后一个返回值。

Go 的惯例，在处理错误时，通常是将返回的错误与 `nil` 比较。`nil` 表示没有错误发生，非 `nil` 表示出现了错误。

程序输出
```go
open /test.txt: No such file or directory
```
## 错误类型的表示
`error` 是一个接口类型
```go
type error interface {  
    Error() string      //接口中的方法签名
}
```
`error` 有了一个签名为 `Error() string` 的方法。所有实现该接口的类型都可以当作一个错误类型。`fmt.Println` 打印错误时，会在内部调用 `Error() string` 方法来输出该错误的描述。